Make mp-analyze exit quickly if it's not needed

diff --git a/scripts/mp-plot b/scripts/mp-plot
--- a/scripts/mp-plot
+++ b/scripts/mp-plot
@@ -10,12 +10,10 @@ cd "$1"
 [[ -e test.txt ]] || { echo "Given test directory is not valid"; exit 1; }
 tests=(*.dat)
 
-if [[ ! -e "${tests[0]}"  ]]; then
-  "$base/mp-analyze" .
-  if [[ $? -gt 0 ]]; then
-    echo "Failed to analyze data - invalid test?"
-    exit 1
-  fi
+"$base/mp-analyze" .
+if [[ $? -gt 0 ]]; then
+  echo "Failed to analyze data - invalid test?"
+  exit 1
 fi
 
 int=$(cat test.txt | grep interrupt | wc -l)
