Make host handling and tcpdump starting more robust

diff --git a/scripts/mp-run b/scripts/mp-run
--- a/scripts/mp-run
+++ b/scripts/mp-run
@@ -56,7 +56,7 @@ fi
 
 if [[ -z $3 ]]; then
   echo -en "==> Detecting testing server: "
-  ap=`iwconfig 2>/dev/null | grep "ESSID:" | grep -- "-wifi" | sed 's/^.*ESSID:"\(.*\)-wifi".*$/\1/'`
+  ap=`iwconfig 2>/dev/null | grep "ESSID:" | grep -- "-wifi" | sed 's/^.*ESSID:"\(.*\)-wifi".*$/\1/' | head -n1`
 
   if [[ -z $ap ]]; then
     echo -e "\e[1;31mundetectable\e[0m"
@@ -106,6 +106,17 @@ echo -e "\e[37m done\e[0m"
 
 echo -e "==> Starting services"
 
+echo -en "  -> Starting tcpdump...\t\t"
+sudo $base/mp-tcpdump -tt -qni any tcp and host $ap 2>/dev/null > tcpdump.pcap &
+if [[ $? -gt 0 ]]; then
+  echo -e "\e[31m fail\e[0m"
+  cd ..
+  rm -rf "$testname-$direction"
+  exit 1
+else
+  echo -e "\e[37m done\e[0m"
+fi
+
 netserver_started=`pidof netserver`
 if [[ $direction == "down" && -z "$netserver_started" ]]; then
   echo -ne "  -> Starting local netserver...\t"
@@ -115,10 +126,6 @@ if [[ $direction == "down" && -z "$netserver_started" ]]; then
 else
   netserver_started=0
 fi
-
-echo -en "  -> Starting tcpdump...\t\t"
-sudo $base/mp-tcpdump -tt -qni any tcp and host $ap 2>/dev/null > tcpdump.pcap &
-echo -e "\e[37m done\e[0m"
 
 echo -en "  -> Starting stats gatherer...\t\t"
 $base/mp-stats 1s $ap > stats.log &
